### ISSUE TITLE
repository에서 jar 파일 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by lhm7877** [shineware/KOMORAN#103]
## 문제 설명
jar 파일이 안받아집니다.

## 재현 경로
_어떻게 하면 동일한 문제가 계속 발생하나요?_
maven reimport

## 기대 상황
jar 파일 로컬 repository에 다운로드

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전: 윈도우 10
* Komoran 버전: 3.3.4, 3.3.9
* Java 버전: 8+

## 추가 정보
pom.xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.shin285</groupId>
            <artifactId>KOMORAN</artifactId>
            <version>3.3.4</version>
        </dependency>
    </dependencies>
결과 : 
Cannot resolve com.github.shin285:KOMORAN:3.3.4

**Comment by lhm7877** [comment]
pom.xml 정보가 잘못 올라갔네요.
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.shin285</groupId>
            <artifactId>KOMORAN</artifactId>
            <version>3.3.4</version>
        </dependency>
    </dependencies>

**Comment by shin285** [comment]
불편을 드려서 죄송합니다. 현재 repository가 shin285에서 shineware로 변경됨에 따라 해당 이슈를 #93 을 통해서 확인 중에 있습니다. 빠른 시일 내에 확인해보도록 하겠습니다.

**Comment by lhm7877** [comment]
@shin285 빠른 답변 감사합니다.

**Comment by shin285** [comment]
@lhm7877 확인 결과 현재 위에 스크린샷에 올려주신 pom.xml 내용 및 `com.github.shin285`를 `com.github.shineware`로 변경하여도 정상적으로 동작하는 것을 확인하였습니다. 혹시 가능하시다면 `pom.xml `의 전체 내용을 알려주실 수 있으실까요? 아래는 제가 테스트에 사용했던 `pom.xml` 내용입니다. 참고부탁드립니다. `.xml` 파일 형식이 업로드가 되지 않아서 뒤에 `.txt`확장자를 추가하였습니다.

[pom.xml.txt](https://github.com/shineware/KOMORAN/files/4393416/pom.xml.txt)

**Comment by shin285** [comment]
별도 의견이 없고 이슈가 아닌 것으로 테스트 되었기 때문에 해당 이슈는 종료하겠습니다.
