### ISSUE TITLE
Elasticsearch tokenizer 플러그인 개발

### ISSUE THREAD

**Issue by shin285** [shineware/KOMORAN#110]
## 기능 설명
- Elasticsearch의 tokenizer 플러그인 개발

## 추가 정보
https://github.com/shineware/komoran-tokenizer 참조

**Comment by dolpang2** [comment]
구체적인 sub-task 정의가 필요할 것 같습니다. 이미 MVP 버전은 구현하신 것 같은데, 아래 3개 이외의 To-do list가 더 있을까요?
- 문서화
- 리팩토링
- KOMORAN 저장소에 integration

**Comment by shin285** [comment]
@dolpang2 말씀하신 3가지 정도면 KOMORAN에 integration 된 상태에서 elasticsearch 플러그인을 테스트해볼 수 있을 것 같습니다.

**Comment by shin285** [comment]
komoran elasticsearch plugin 설치 후 elasticsearch 실행까지 가능하나,
analyze 테스트 시 NullPointException이 발생
Request:
![image](https://user-images.githubusercontent.com/8907756/80310404-88db8500-8815-11ea-9a0c-d35dc694c370.png)
Response:
![image](https://user-images.githubusercontent.com/8907756/80310409-91cc5680-8815-11ea-9f55-c382a66315bc.png)

Request의 text parameter 값이 전달이 되지 않는 것으로 확인
원인 분석 및 해결 필요

issue-110 branch의 7c3f9cb5d16036559b034a74d43b30e2d7efea25 commit에서 재현 가능

**Comment by shin285** [comment]
@dolpang2 근호님 컴퓨터에서 한번 테스트 해보실 수 있나요?

**Comment by dolpang2** [comment]
@shin285 넹 테스트 후에 코멘트달게요

**Comment by shin285** [comment]
Elasticsearch 7.6.2에서 empty string을 통해 plugin의 version을 체크하는 로직이 추가되었습니다.
이 때 KOMORAN에서 empty string에 대한 버그가 있었기 때문에 NPE가 발생하는 것을 확인하였습니다. #119 이슈를 통해 KOMORAN에서 발생하는 버그를 해결하였습니다.
