### ISSUE TITLE
사용자 사전을 통해 기호 &을 포함하는 단어 인식이 되지 않습니다. 

### ISSUE THREAD

**Issue by moveslike15** [shineware/KOMORAN#128]
## 문제 설명
사용자 사전을 통해서 기호를 포함하는 단어를 인식시키려고 했는데 작동을 하지 않습니다. "R&D"나 "M&A"처럼 기호 &를 포함하고 있는 명사들을 인식시키려고 했는데 인식을 못하고 R, D, M, A, &로 분리해서 인식됩니다. 

## 재현 경로
_어떻게 하면 동일한 문제가 계속 발생하나요?_
저는 utf-8로 된 userdic.txt 파일을 만들고 이것을 메모장 혹은 엑셀로 편집하여 
R&D\tNNG
M&A\tNNG
같은 식으로 입력하였습니다. 그 다음 문서 파일을 토큰화하였습니다.

## 기대 상황
위와 같이 사용자 사전에 입력한 대로 R&D, M&A 등 기호로 연결된 문자들이 하나의 단어로 인식되어야 한다고 생각합니다.

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전: 윈도우즈 10 Home
* 브라우저 종류 및 버전: 
* Komoran 버전: konlpy==0.5.2 을 통해 20년 7월 말에 설치했는데 Komoran 버전을 어떻게 확인하는지 모르겠습니다. 
* Java 버전: Java SE Development Kit 14.0.2, JPype1==1.0.1

## 추가 정보
_스크린샷이나 에러 로그 등, 추가 정보가 있다면 남겨주세요._

**Comment by shin285** [comment]
혹시 사용자 사전에 다른 단어들을 넣었을때는 정상적으로 인식하나요?

**Comment by moveslike15** [comment]
예 다른 단어들은 정상적으로 동작합니다.

**Comment by shin285** [comment]
konlpy의 이슈로 보입니다. KOMORAN에서는 정상적으로 동작하고 있네요.
![image](https://user-images.githubusercontent.com/8907756/89636466-a4116280-d8e3-11ea-8fd7-a2647385f7a2.png)
python이 필요하신 상황이라면 https://github.com/shineware/PyKOMORAN 사용을 추천드립니다:)

**Comment by moveslike15** [comment]
확인해주셔서 감사합니다. Komoran이 제대로 작동할 수 있도록 다른 방식으로 한번 코드를 만들어 보겠습니다.

**Comment by dolpang2** [comment]
KOMORAN 이슈가 아니므로 티켓 클로즈 합니다.
