### ISSUE TITLE
"안녕하세요" 문장의 분석 결과

### ISSUE THREAD

**Issue by spark323** [shineware/KOMORAN#130]
안녕하세요. 형태소 분석을 이용하던 도중 의아한 점이 있어서 여쭤보려 합니다.

"안녕하세요." 가 안녕하세요/IC 로 분석됩니다.  한글 문법을 정확히 알지 못해  올바른 분석인지 여쭈어봐도 될까요?

* Komoran 버전: 3.3.9

**Comment by shin285** [comment]
안녕하세요.
보는 관점에 따라서 "안녕하세요"가 안녕하세요/IC로 또는 안녕+ 하+시+어요와 같은 형태소 분석이 될 수 있습니다만,
현재 KOMORAN은 안녕하세요/IC로 분석 중입니다.
그러나 저 뿐만 아니라 대부분이 안녕+하+시+어요와 같은 분석 결과가 관련 업무 관점에서는 더 적합할 것으로 생각되네요.
위 내용 빠른 시일 내에 패치하도록 하겠습니다!
리포팅 감사합니다.
cc @songyonge

**Comment by spark323** [comment]
정말 감사합니다!
