### ISSUE TITLE
`제이시바이오텍 클라딕스 스캘프 클렌징 샴푸`가 원하는 대로 분석이 되지 않습니다

### ISSUE THREAD

**Issue by ImSejin** [shineware/KOMORAN#132]
## 문제 설명
```text
제이시바이오텍 클라딕스 스캘프 클렌징 샴푸
```

위의 문장의 형태소를 분석한 결과, 아래와 같이 나옵니다.

```text
제/NP 이/VCP 시바이/NNP 오텍/NNP 크/VA ㄹ라/EC 딕스/NNP 스/NNG 캐/VV ㄹ/ETM 프/NNP 클렌징/NNG 샴푸/NNP
```

## 재현 경로
```java
// given
Komoran komoran = new Komoran(DEFAULT_MODEL.FULL);
String sentence = "제이시바이오텍 클라딕스 스캘프 클렌징 샴푸";

// when
KomoranResult result = komoran.analyze(sentence);

// then
System.out.println(sentence);
System.out.println(result.getPlainText());
```

## 기대 상황
저는 둘 중 하나로 분석되어야 한다고 생각합니다.

1. `제이시/바이오/텍/클라딕스/스캘프/클렌징/샴푸`
2. `제이시바이오텍/클라딕스/스캘프/클렌징/샴푸`

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전: Windows 10 Pro
* 브라우저 종류 및 버전: Chrome 64bit 96.0.4664.45
* Komoran 버전: 3.3.9
* Java 버전: OpenJDK 1.8.0_292

**Comment by shin285** [comment]
안녕하세요! 현재 "제이시바이오텍"이 미등록어여서 위와 같이 분석되는 것으로 보여집니다.
해당 내용 업데이트하여 반영하도록 하겠습니다!
감사합니다

**Comment by ImSejin** [comment]
답변 감사합니다.

1. 반영된다면 `제이시/바이오/텍`, `제이시바이오텍` 둘 중 어느 것으로 분리되는 건가요?
2.  `클라딕스/스캘프`가 `크/VA ㄹ라/EC 딕스/NNP 스/NNG 캐/VV ㄹ/ETM 프/NNP`로 분리되는 것은 어떻게 되는 건가요?

P.S. 다양한 상품의 이름을 형태소 분석을 하고 있는데, 학습에 도움이 된다면 데이터를 제공할 의향이 있습니다.

**Comment by shin285** [comment]
1. `제이시바이오텍`의 경우에는 고유명사이기 때문에 `제이시바이오텍`으로 분석되게 하려고 하고 있습니다.
2. `클라딕스 스켈프`의 경우에도 `클라딕스/NNP`와 `스켈프/NNP`로 분석되게 하고자 합니다.
3. 말씀 주신 예제에는 띄어쓰기가 전혀되어있지 않기 때문에 형태소 분석 전에 띄어쓰기가 먼저 진행되어야합니다. 제품명에 대해서 형태소 분석을 하시는 경우라면 분절된 단어들을 사용자 사전에 추가하시면 도움이 되실 것 같습니다.


갖고 계신 데이터가 어떤 데이터인지 확실치 않아서 학습에 도움이 될지 여부는 검토 후에 판단을 해봐야할 것 같습니다 :)

**Comment by ImSejin** [comment]
이메일로 샘플 데이터 보내드렸습니다.

검토 후 적합하다고 판단되시면 연락주세요 :)

**Comment by shin285** [comment]
샘플 데이터 면밀히 검토를 해봤으나 띄어쓰기가 포함되어 있지 않은 단어들이 많아서 범용적으로 사용하기에는 어려울 것 같습니다 ㅠ
관심 가져주시고 적극적으로 참여해주셔서 감사드립니다!
