### ISSUE TITLE
안녕하세요 안드로이드 스튜디오에서 코모란을 써보려고 합니다.

### ISSUE THREAD

**Issue by minminjao** [shineware/KOMORAN#136]
## 문제 설명
_무엇이, 어떻게 문제인가요? 안드로이드 스튜디오 내에서 설치를 해보려고 하는데 처음부터 막혀서요
https://github.com/shineware/KOMORAN/issues/134 <-- 이것을 참고해서 설치를 하려고 하는데 allprojects부터가 없어서 여쭤봅니다 (제 buil.gradle의 앱에서는 allproject를 설치를 setting.gradle에 입력하여 해결을 하였습니다 이렇게 하면 되는 걸까요? .) 
<제꺼 설치>
![image](https://user-images.githubusercontent.com/108252034/232441131-a1d343cd-3d1a-42bc-80a3-bf815584c628.png)

위에를 설치하는데는 성공하였고 밑의 코드를 build.gradle(app)쪽에서 하려니 에러가 납니다. 혹시 어떻게 하면 되는건지 알수있을까요?

dependencies {
  implementation 'com.github.shin285:KOMORAN:3.3.4'
}
<밑에는 참고 이슈>
![image](https://user-images.githubusercontent.com/108252034/232438245-aeb4d708-a761-442a-8a50-afeea2c17bfc.png)

## 재현 경로
_어떻게 하면 동일한 문제가 계속 발생하나요?_
* '...'로 이동합니다.
* '...'을 누릅니다.
* '...'을 볼 수 있습니다.

## 기대 상황
_정상적인 상황에서는 어떻게 동작해야 한다고 생각하세요?_

## 환경 정보

* Komoran 버전: 최신버전
* Java 버전: 안드로이드 스튜디오내 최신버전을 사용할 예정이며 현재 다른 코틀린으로 코드를 작성중입니다.
*  찾아보니 코틀린과 자바를 섞어서 사용(?)이 가능하다고 해서 그렇게 해보려고 합니다.

## 추가 정보
설치자체가 안되면 에러가 뜸

**Comment by dolpang2** [comment]
@minminjao 안녕하세요 리포팅 감사합니다. 개발하시는 안드로이드 프로젝트의 build.gradle 파일 전체를 혹시 올려주실 수 있을까요? 그러면 문제 해결에 도움이 될 것 같습니다

**Comment by minminjao** [comment]
안녕하세요 파일전체 코드복사해서 올립니다.

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.androidstt'
    compileSdk 33
    buildFeatures{
        viewBinding true
    }
    defaultConfig {
        applicationId "com.example.androidstt"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation platform('com.google.firebase:firebase-bom:31.3.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-database-ktx'

    def camerax_version = "1.1.0-beta01"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-video:${camerax_version}"

    implementation "androidx.camera:camera-view:${camerax_version}"
    implementation "androidx.camera:camera-extensions:${camerax_version}"

}

**Comment by minminjao** [comment]
안녕하세요 써주신 코모란 의존성을 추가하니 이러한 에러가 발생하였습니다.
![image](https://user-images.githubusercontent.com/108252034/232463506-c4ad2627-3c26-46ab-9fe0-ea7a6b84c3ee.png)

**Comment by minminjao** [comment]
![image](https://user-images.githubusercontent.com/108252034/232463629-934c5b6b-6391-4f50-86a2-64a17fe1df9c.png)

**Comment by dolpang2** [comment]
> 안녕하세요 써주신 코모란 의존성을 추가하니 이러한 에러가 발생하였습니다. ![image](https://user-images.githubusercontent.com/108252034/232463506-c4ad2627-3c26-46ab-9fe0-ea7a6b84c3ee.png)

이거 제가 Android 개발 환경 세팅을 직접 해보고 테스트한 후에 다시 답변드려도 괜찮을까요?

**Comment by minminjao** [comment]
네 당연하죠 그렇게 해주신다면 저야 영광입니다!

**Comment by shin285** [comment]
안녕하세요. 혹시 버전을 3.3.9로 변경해서 시도해보실 수 있으실까요?
그래도 안된다면 아래와 같이 수정도 한번 해보시겠어요?!
implementation('com.github.shin285:KOMORAN:3.3.4') {
    exclude group: 'com.github.shineware', module: 'commons'
    exclude group: 'com.github.shineware', module: 'aho-corasick'
}

**Comment by minminjao** [comment]
안녕하세요 혹시 둘다 안된다면 어떻게 해야할까요..혹시 선생님 측에서는 되셨나요?

**Comment by minminjao** [comment]
![image](https://user-images.githubusercontent.com/108252034/232467130-6bdfd9c2-f391-47b5-9a3a-09748a4fcea7.png)
아니면면 제가 setting:build에서 실수했을까 싶어서 올립니다

**Comment by minminjao** [comment]
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "androidstt"
include ':app'

setting:build의 풀코드입니다..

**Comment by shin285** [comment]
어떤 경우에는 되고 어떤 경우에는 안되고 그런 상황들이 너무 자주 연출이 되어서...ㅠ 일단 dolpang2 님의 답변을 기다려봐야겠어요..ㅠ

**Comment by minminjao** [comment]
네 알겠습니다 도와주셔서 감사합니다

**Comment by minminjao** [comment]
혹시 이거 다르게 해결하신분들이 계신가요..? 아무리 해도 안되네요

**Comment by dolpang2** [comment]
> 혹시 이거 다르게 해결하신분들이 계신가요..? 아무리 해도 안되네요

코드 관리하시는 분들이 모두 백엔드 엔지니어라 안드로이드 개발 환경에서는 충분히 테스트가 없었습니다 ㅠ_ㅠ 일반적인 Java/Kotlin 환경에서는 [설치 문서 가이드](https://docs.komoran.kr/firststep/installation.html?utm_source=komoran-repo&utm_medium=Referral&utm_campaign=github-demo#gradle)대로면 동작하는 것을 확인했는데, 안드로이드는 뭔가 다른 부분이 있는 지 확인이 필요한 상태입니다. 주말까지는 제 개인 환경에 셋업 후 다시 답변드리겠습니다

**Comment by minminjao** [comment]
아니면  밑 사진의 코드를 build.gradle(app)에만 다 작성하면 되나요? 혹시 선생님의 build.gradle(app)코드나 작성하신 코드를 볼수있을까요?

 ![Screenshot_20230420_113602_GitHub.jpg](https://user-images.githubusercontent.com/108252034/233243515-f56a78ae-408f-4ac6-a67d-d6fb44a0d21f.jpg)

**Comment by dolpang2** [comment]
안녕하세요, 잠깐 짬이 나서 빠르게 테스트를 해봤는데요. 정리해서 말씀드리면 KOMORAN 3.3.9 버전에서는 동작을 확인했고, 3.3.4의 경우에는 실패합니다.

![3_3_4_error](https://user-images.githubusercontent.com/9076745/233245877-a0c5a7d6-a0fe-45f2-9b66-7714ee935666.png)
![3_3_9_running](https://user-images.githubusercontent.com/9076745/233245883-75662957-ea46-4af7-8a40-65c613d168e5.png)

아래 두 가지 파일을 수정했으며, 전체 테스트 저장소는 다음을 참고하세요 ( https://github.com/dolpang2/android-with-komoran )
- settings.gradle ( https://github.com/dolpang2/android-with-komoran/blob/f64ae42c79ddde6bedb28794ea8dbcd8371a93c9/settings.gradle#L13 )
- build.gradle ( https://github.com/dolpang2/android-with-komoran/blob/f64ae42c79ddde6bedb28794ea8dbcd8371a93c9/app/build.gradle#L67 )

**Comment by minminjao** [comment]
네 감사합니다 제꺼에서 다시 시도해보겠습니다
혹시나 싶어 제가 지금 하고 있는 안드로이드 스튜디오 프로젝트 링크 올립니다..!

https://github.com/minminjao/androidstt

(제측에서 실수한것일수도 있으므로..!)
문제 파악에 도움될까 싶어 올립니다.

**Comment by minminjao** [comment]
방금 알려주신대로 했는데 설치가 성공적으로 되었습니다 제가 settings:gradle의 코드작성부분을 잘못 쓴것같아요 ㅜㅜ 도와주셔서 감사합니다!

**Comment by dolpang2** [comment]
> 방금 알려주신대로 했는데 설치가 성공적으로 되었습니다 제가 settings:gradle의 코드작성부분을 잘못 쓴것같아요 ㅜㅜ 도와주셔서 감사합니다!
> 
> 그런데 한가지 더 궁금한게 있는데 이게 실시간 입력받은걸 파이어베이스에 저장시킨걸 형태소 분석을 하려면 게시글인 "3분만에 형태소 분석따라하기"를 참고하면 될까요?

해결이 되셨다니 다행이네요. 형태소 분석은 말씀하신 3분만에 형태소 분석 따라하기와 [분석 예제](https://docs.komoran.kr/examples/analyze.html) 두 가지를 참고하시면 될 것 같습니다. KOMORAN에서 제공하는 API의 자세한 정보는 다음 페이지를 참고하세요 [link](https://docs.komoran.kr/api/kr/co/shineware/nlp/komoran/core/Komoran.html#methods)

**Comment by dolpang2** [comment]
기존 이슈에서 알려주신 문제에 대해서는 해결된 것으로 보여 본 이슈는 닫습니다
필요하다면 이슈를 다시 열거나, 신규 이슈를 작성해서 주시면 됩니다.
