### ISSUE TITLE
코모란 어드민 페이지 개발

### ISSUE THREAD

**Issue by shin285** [shineware/KOMORAN#4]
트레이닝 데이터, 사용자 사전, 기분석 사전을 관리하기 위한 코모란 어드민 페이지가 필요합니다....ㅠㅠ
별도의 repository(project)로 생성되어지길 간절히..아주 간절히 바랍니다..ㅠ

**Comment by 9bow** [comment]
트레이닝 데이터(단어) 파일을 수정을 위한 [DictAdmin](https://github.com/9bow/DictAdmin)을 node.js로 만들었습니다. Java/SpringBoot로 변경 후 다른 기능들을 추가하도록 하겠습니다.

**Comment by hnccho** [comment]
코모란 어드민 페이지에 필요한 기능이 어떻게 되나요? 제 홈페이지에 일단 분석 서비스 기능을 추가했습니다. 조금만 수정하면 어드민 페이지도 만들 수 있을 것 같습니다. 그리고 스프링 프레임워크에 서비스 기능을 추가하면서 코모란을 조금 손보았는데 현재 코모란은 Komoran클래스를 생성할 때 마다 매번  사전 데이터를 메모리에 올리도록 되어 있습니다. 하지만 이를 서비스 프로그램으로 바꾸면 사전데이터를 매번 읽을 필요없이 처음 부팅될 때 한번만 읽도록 할 수 있기 때문에 분석이 더 쉽게 진행될 수 있습니다. 구현은 다음 사이트를 참조하시기 바랍니다. 
구현 : http://www.aramsoft.co.kr
소스:  http://github.com/aramsoft/aramcomp

**Comment by shin285** [comment]
@hnccho 현재 코모란 어드민은 https://github.com/shineware/KOMORANAdmin 으로 개발되어있습니다. 추가적으로 개발이 필요한 사항들은 해당 repository에 이슈로 등록되어 있습니다. 그리고 Komoran 객체는 한번만 생성하여 analyze를 재사용하도록 되어있습니다. analyze를 위해서 매번 Komoran 객체를 생성할 필요는 없습니다 :) 관심가져주시고 지속적으로 피드백 주셔서 진심으로 감사드립니다. @9bow 님 이슈 사항이 없으면 현재 이슈 close 부탁드립니다 👍

**Comment by hnccho** [comment]
분석을 위한 서비스 클래스 초기화 함수에서 객체 생성을 한번 한 후 그 객체를 사용하도록 하면 되겠네요. 감사합니다.

**Comment by 9bow** [comment]
@hnccho 
관심 감사합니다! 필요하신 기능 또는 제안하실 내용이 있으시다면 위 KOMORANAdmin 저장소에 이슈 또는 PR 부탁드립니다.
이 이슈는 닫도록 하겠습니다. (_ _)
