### ISSUE TITLE
Supporting for R environment as package

### ISSUE THREAD

**Issue by dolpang2** [shineware/KOMORAN#47]
R 환경의 유저 지원을 위한 Wrapping Package 지원

**Comment by mrchypark** [comment]
안녕하세요, 제가 부족한 솜씨를 가지고 있습니다만... 혹시 제가 R 패키지화 부분에 참여해도 괜찮을까요?

**Comment by dolpang2** [comment]
안녕하세요 @mrchypark 님. 현재 R wrapping package를 작업 중이고 빠른 시일 내에 devtool::install_github 및 CRAN으로 배포 가능하게 지원 예정입니다. 해당 repository에 곧 코드 베이스를 공개할 예정이니 그곳으로 컨트리뷰션 해주시면 좋을 것 같습니다!

**Comment by mrchypark** [comment]
@dolpang2 아 그렇군요! 그럼 기대하면서 기다리도록 하겠습니다. 감사합니다.

**Comment by dolpang2** [comment]
@shin285 시간이 벌써 이렇게 지났군요; 우선 기능 구현 자체는 완료되었는데 CRAN에 올리지 않은 것이 남은 상태입니다. CRAN에 배포하려면 몇 가지 요구사항 (단위 테스트, 문서화 등)이 더 필요하고요. 해당 이슈는 우선 닫고 CRAN 배포 관련 이슈를 새로 따는 게 좋을 것 같습니다. 어떻게 생각하세요? BETA를 CRAN에 올리고 뗄지 아니면 우선 뗄지도 논의는 필요하겠네요.

**Comment by shin285** [comment]
베타는 떼는게 좋을 것 같습니다! 베타로 했다가 나중에 베타 버전이랑 차이가 없는 상태로 릴리즈 하면 애매해 질 것 같아요.

**Comment by dolpang2** [comment]
@shin285 RKOMORAN의 description의 beta 내용은 제거했습니다. Follow up ticket으로 README update 및 CRAN 배포 관련 이슈 우선 생성해둘게요. 본 티켓은 close합니다
