### ISSUE TITLE
사용자 사전 등록 오류

### ISSUE THREAD

**Issue by dnwnquf** [shineware/KOMORAN#73]
## 기능 설명
_어떤 상황에서, 무엇을 추가하거나 / 변경하길 원하시나요?_

사용자 사전을 다음과 같이 등록하였으나, 반영된 결과가 나오지 않습니다.
참고로, /t이 4번의 공백으로 변환하도록 설정이 되어있는 상태입니다.
komoran.setUserDic("src/main/res/raw/dic.user");

## 추가 정보
_참고할 수 있는 다른 정보가 있다면 남겨주세요._

**Comment by shin285** [comment]
사용하고 계신 IDE에서 \t 대신 4번의 공백으로 변환되도록 하는 설정을 소스 파일에만 적용시키면 \t을 그대로 사용하실 수 있습니다.

**Comment by jis1218** [comment]
> 사용하고 계신 IDE에서 \t 대신 4번의 공백으로 변환되도록 하는 설정을 소스 파일에만 적용시키면 \t을 그대로 사용하실 수 있습니다.

혹시 어떤 의미인지 알 수 있을까요?
저 같은 경우 같은 IDE(Visual Studio Code)에서 작업을 하고 있는데
fwd.user는 잘 동작하지만 dic.user는 동작하지 않네요
```
Komoran komoran = new Komoran(DEFAULT_MODEL.LIGHT);

		komoran.setUserDic("C:\\Users\\beplu\\Desktop\\dic.user");
		komoran.setFWDic("C:\\Users\\beplu\\Desktop\\fwd.user");
		String lastWord = "정인섭";
		List<Token> tokens = komoran.analyze(lastWord).getTokenList();
		
		for(Token token : tokens) {
			System.out.println(token.getMorph() + " / " + token.getPos());
	}
```

**Comment by shin285** [comment]
code editor에서 탭을 넣어도 공백 4개로 치환하는 기능이 있는 경우가 있기 때문에 위와 같이 가이드를 드렸습니다만, fwd.user가 잘 동작하는데 dic.user가 동작하지 않는 것은 조금 이상하네요. 결과 화면 스크린샷 첨부해주실 수 있으실까요?

**Comment by jis1218** [comment]
> code editor에서 탭을 넣어도 공백 4개로 치환하는 기능이 있는 경우가 있기 때문에 위와 같이 가이드를 드렸습니다만, fwd.user가 잘 동작하는데 dic.user가 동작하지 않는 것은 조금 이상하네요. 결과 화면 스크린샷 첨부해주실 수 있으실까요?

빠른 답변 감사드립니다.
스크린샷 첨부드립니다!

![캡처1](https://user-images.githubusercontent.com/31408300/78099401-bdc60900-741c-11ea-817b-2b6e545bc2a0.PNG)
![캡처2](https://user-images.githubusercontent.com/31408300/78099406-bef73600-741c-11ea-8ee0-cbbf2805306c.PNG)
![캡처3](https://user-images.githubusercontent.com/31408300/78099407-bef73600-741c-11ea-962e-08aee4627d5e.PNG)

**Comment by shin285** [comment]
코드나 파일 상에는 문제가 없어보이는데요..스크린샷에서 사용하신 dic.user 파일을 업로드해주실 수 있으실까요? github에서는 .user 확장자로는 업로드가 안되니 .txt 확장자로 변경하시면 됩니다. 업로드 해주시면 테스트 진행해보도록 하겠습니다. 아니면 KOMORANAdmin을 통해서 사전 편집 및 업로드/다운로드가 가능하니 해당 툴을 이용해보시는 것을 추천드립니다.

**Comment by jis1218** [comment]
[dic_user.txt](https://github.com/shineware/KOMORAN/files/4418409/dic_user.txt)

파일 올려드렸습니다.
확인해주셔서 감사합니다!
그리고 코모란Admin이란 툴도 있었군요! 사용해보겠습니다.
감사합니다.

**Comment by shin285** [comment]
올려주신 사용자 사전을 적용하였을 때 정상적으로 동작하는 것을 확인하였습니다. 파일 인코딩 문제로 예상했는데 인코딩 문제는 아닌 것 같네요. 
![image](https://user-images.githubusercontent.com/8907756/78311113-eb30c500-758a-11ea-83f6-69fcd944eb5c.png)
![image](https://user-images.githubusercontent.com/8907756/78311124-f3890000-758a-11ea-827c-e4a272e222d7.png)

혹시 사용자 사전 말고 기분석 사전도 동작하는지 확인이 가능할까요? 만약에 기분석 사전도 동작을 안하고 있다면 프로젝트가 UTF-8로 세팅이 안 되어있는 경우를 생각해볼 수 있을 것 같아요. 프로젝트가 UTF-8이 아닌 MS949로 되어있다면 파일 로딩도 MS949로 할 가능성이 매우 높습니다.

**Comment by jis1218** [comment]
말씀해주신대로 프로젝트의 텍스트 인코딩이 MS949로 되어있었네요.
UTF-8로 변경 후 해보니 잘 됩니다~
그럼에도 기분석 사전이 잘 동작하는 건 여전히 이상하네요ㅎㅎ(아마 제가 설정을 잘못 해줬겠죠)

도움 많이 주셔서 정말 감사드립니다.
그리고 알려주신 Admin도 잠깐 써봤는데 큰 도움이 될 것 같습니다.

수고하세요!!!

**Comment by shin285** [comment]
해결되었다니 다행이네요. 추후에 또 문의 사항이 있으시면 언제든지 이슈로 등록 부탁드립니다. 감사합니다 :)
