### ISSUE TITLE
Porting the model to TensorFlow

### ISSUE THREAD

**Issue by atn832** [shineware/KOMORAN#84]
Would it be possible to convert the model to the TensorFlow file format, so that we can run it with TensorFlow? This would have a few advantages like:
- being able to run the model natively on a phone without an API server.
- being able to run the model in a web application without an API server.
- serving the model as an API without dependencies like the JDK (https://www.tensorflow.org/tfx/serving/docker)

Older post:
## 기능 설명
자바 대신에 TensorFlow모델로 출시 할수 있어요?

## 추가 정보
TensorFlow모델로 만들면 쉽게:
* API로 돌릴수 있어요 (https://www.tensorflow.org/tfx/guide/serving). https://github.com/9bow/KOMORANRestAPIServer 좋은데 JDK, 자바dependencies이나 gradle등등 좀 복잡해요.
* 서버 없이 앱에서 돌릴수 있어요 (https://www.tensorflow.org/lite)
* 서버 없이 사이트에서 돌릴수 있어요 (https://www.tensorflow.org/js)

**Comment by dolpang2** [comment]
Hi @atn832  
It's ok to rewrite your requirement as English. Can you do it again? It's little bit ambiguous to find your intention of initial draft. Thanks in advance!

**Comment by dolpang2** [comment]
I'm not very sure your intent, but if you are familiar with using Python you can use https://github.com/shineware/PyKOMORAN

**Comment by atn832** [comment]
Sure, just updated my comment. Thank you!

For now I'm actually using https://github.com/9bow/KOMORANRestAPIServer.

**Comment by 9bow** [comment]
Hi, @atn832 

Are there any issues with using KOMORAN? If you have any progress, could you share with us some KOMORAN related Tensorflow project or something? It may help other users. :D
Also, I will close this issue if there is no more issue. Thanks.
